# .github/workflows/blank.yml
name: YouTube Downloader
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube URL'
        required: true
      file_format:
        description: 'mp4 or mp3'
        required: true
        default: 'mp4'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Download Process
        env:
          COOKIES_B64: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          # המרת ה-Base64 חזרה לקובץ עוגיות
          echo "$COOKIES_B64" | base64 --decode > cookies.txt
          
          if [ "${{ github.event.inputs.file_format }}" = "mp3" ]; then
            yt-dlp -x --audio-format mp3 --cookies cookies.txt "${{ github.event.inputs.video_url }}" -o "downloaded_file.mp3"
          else
            yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --cookies cookies.txt "${{ github.event.inputs.video_url }}" -o "downloaded_file.mp4"
          fi

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: youtube-download
          path: downloaded_file.*
